from django.conf import settings

DEFAULT_SUBSTITUTION_USER_SESSION_KEY = 'SUBSTITUTION_USER'
SUBSTITUTION_USER_SESSION_KEY = getattr(settings, 'SUBSTITUTION_USER_SESSION_KEY',
                                        DEFAULT_SUBSTITUTION_USER_SESSION_KEY)

DEFAULT_SUBSTITUTION_USER_REQUEST_REAL_USER_KEY = 'REAL_USER'
SUBSTITUTION_USER_REQUEST_REAL_USER_KEY = getattr(settings, 'SUBSTITUTION_USER_REQUEST_SUBSTITUTION_USERER_KEY',
                                                  DEFAULT_SUBSTITUTION_USER_REQUEST_REAL_USER_KEY)

DEFAULT_SUBSTITUTION_USER_REDIRECT_PATH = '/'
SUBSTITUTION_USER_REDIRECT_PATH = getattr(settings, 'SUBSTITUTION_USER_REDIRECT_PATH',
                                          DEFAULT_SUBSTITUTION_USER_REDIRECT_PATH)

DEFAULT_SUBSTITUTION_USER_REQUEST_PATH_EXCLUDES = ['/admin/']
SUBSTITUTION_USER_REQUEST_PATH_EXCLUDES = getattr(settings, 'SUBSTITUTION_USER_REQUEST_PATH_EXCLUDES',
                                                  DEFAULT_SUBSTITUTION_USER_REQUEST_PATH_EXCLUDES)

DEFAULT_SUBSTITUTION_USER_ADMIN_COLUMN_NAME = 'SU AS'
SUBSTITUTION_USER_ADMIN_COLUMN_NAME = getattr(settings, 'SUBSTITUTION_USER_ADMIN_COLUMN_NAME',
                                              DEFAULT_SUBSTITUTION_USER_ADMIN_COLUMN_NAME)
